import { exec } from 'node:child_process'
import * as http from 'node:http'
import { URL } from 'node:url'
import { promisify } from 'node:util'
import * as client from 'openid-client'
import { CliError } from './errors.js'

const execAsync = promisify(exec)

const CLIENT_ID = 'lightdash-cli'
const CALLBACK_PATH = '/callback'
const DEFAULT_TIMEOUT_MS = 120_000
const DEFAULT_TOKEN_TTL_HOURS = 24 * 30 // 30 days

export interface OAuthLoginOptions {
  url: string
  oauthPort?: number
  tokenTtlHours?: number
  timeoutMs?: number
  /** Called once the authorization URL is known, before opening the browser. */
  onAuthUrlReady?: (authUrl: string) => void
  /** Called once the local callback server is listening. */
  onServerReady?: (port: number) => void
}

export interface OAuthLoginResult {
  token: string
  expiresAt: Date
  user: {
    userUuid: string
    organizationUuid: string
    email: string
    firstName: string
    lastName: string
  }
}

/**
 * Open a URL in the user's default browser. Silently swallows failures — the
 * URL is always printed to stderr so the user can paste it manually as a
 * fallback.
 */
export async function openBrowser(url: string): Promise<void> {
  try {
    const { platform } = process
    if (platform === 'darwin') {
      await execAsync(`open "${url}"`)
    } else if (platform === 'win32') {
      // start needs an empty title arg when the URL is quoted
      await execAsync(`start "" "${url}"`)
    } else {
      await execAsync(`xdg-open "${url}"`)
    }
  } catch {
    // Intentional: the caller prints the URL before calling us.
  }
}

function successHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>ldash — Signed in</title>
  <style>
    html, body { margin: 0; padding: 0; background: #fafafa; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           color: #111827; display: flex; align-items: center; justify-content: center;
           min-height: 100vh; }
    .card { background: white; border-radius: 12px; padding: 40px 48px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 10px 30px rgba(0,0,0,0.04);
            max-width: 420px; text-align: center; }
    .check { font-size: 56px; color: #10b981; line-height: 1; }
    h1 { font-size: 22px; margin: 16px 0 8px; font-weight: 600; }
    p { color: #6b7280; margin: 8px 0 0; font-size: 14px; line-height: 1.5; }
    .hint { margin-top: 24px; font-size: 13px; color: #9ca3af; }
  </style>
</head>
<body>
  <div class="card">
    <div class="check">✓</div>
    <h1>Signed in to ldash</h1>
    <p>You can close this tab and return to your terminal.</p>
    <p class="hint">Your CLI is finishing up…</p>
  </div>
</body>
</html>`
}

function errorHtml(message: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>ldash — Sign in failed</title>
  <style>
    html, body { margin: 0; padding: 0; background: #fafafa; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           color: #111827; display: flex; align-items: center; justify-content: center;
           min-height: 100vh; }
    .card { background: white; border-radius: 12px; padding: 40px 48px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 10px 30px rgba(0,0,0,0.04);
            max-width: 420px; text-align: center; }
    .x { font-size: 56px; color: #ef4444; line-height: 1; }
    h1 { font-size: 22px; margin: 16px 0 8px; font-weight: 600; }
    p { color: #6b7280; margin: 8px 0 0; font-size: 14px; line-height: 1.5; }
    code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px;
           font-size: 13px; color: #374151; }
  </style>
</head>
<body>
  <div class="card">
    <div class="x">✗</div>
    <h1>Sign in failed</h1>
    <p>${escapeHtml(message)}</p>
    <p>You can close this tab and try again in your terminal.</p>
  </div>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

async function generatePat(
  apiUrl: string,
  accessToken: string,
  hoursToExpire: number,
): Promise<{ token: string; expiresAt: Date }> {
  const expiresAt = new Date(Date.now() + hoursToExpire * 60 * 60 * 1000)
  const now = new Date()
  const response = await fetch(
    new URL('/api/v1/user/me/personal-access-tokens', apiUrl).href,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        expiresAt,
        description: `Generated by ldash on ${now.toISOString().slice(0, 10)}`,
        autoGenerated: true,
      }),
    },
  )
  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new CliError(
      'Failed to create access token',
      `Lightdash returned HTTP ${response.status} when creating a personal access token.${body ? `\n       ${body.slice(0, 200)}` : ''}`,
      'Try again, or fall back to pasting a token manually: ldash setup --pat',
    )
  }
  const body = (await response.json()) as { results: { token: string } }
  return { token: body.results.token, expiresAt }
}

async function fetchUser(
  apiUrl: string,
  pat: string,
): Promise<OAuthLoginResult['user']> {
  const response = await fetch(new URL('/api/v1/user', apiUrl).href, {
    headers: { Authorization: `ApiKey ${pat}` },
  })
  if (!response.ok) {
    throw new CliError(
      'Failed to fetch user info',
      `Lightdash returned HTTP ${response.status} for /api/v1/user after sign-in.`,
      'Try "ldash setup" again. If the problem persists, report an issue.',
    )
  }
  const body = (await response.json()) as {
    results: {
      userUuid: string
      organizationUuid: string
      email: string
      firstName: string
      lastName: string
    }
  }
  return body.results
}

function resolvePort(requested: number | undefined): number {
  if (requested !== undefined) return requested
  const envPortStr = process.env.LIGHTDASH_OAUTH_PORT
  if (!envPortStr) return 0
  const envPort = Number.parseInt(envPortStr, 10)
  if (Number.isNaN(envPort) || envPort < 1 || envPort > 65535) {
    throw new CliError(
      'Invalid LIGHTDASH_OAUTH_PORT',
      `LIGHTDASH_OAUTH_PORT must be a number between 1 and 65535, got "${envPortStr}".`,
      'Unset the env var or pass --oauth-port <n> explicitly.',
    )
  }
  return envPort
}

/**
 * Run the OAuth2 Authorization Code + PKCE flow against a Lightdash instance.
 *
 * Steps:
 *   1. Start a local HTTP server on 127.0.0.1 (random port by default)
 *   2. Build the authorization URL and open the user's browser
 *   3. Wait for the callback (with timeout)
 *   4. Exchange the code for an access token
 *   5. Use the access token to create a long-lived Personal Access Token
 *   6. Fetch user info and return everything
 *
 * The access token from step 4 is short-lived; the returned PAT from step 5
 * is what gets saved to disk for subsequent CLI calls.
 */
export async function loginWithOAuth(
  options: OAuthLoginOptions,
): Promise<OAuthLoginResult> {
  const {
    url,
    tokenTtlHours = DEFAULT_TOKEN_TTL_HOURS,
    timeoutMs = DEFAULT_TIMEOUT_MS,
    onAuthUrlReady,
    onServerReady,
  } = options

  let port = resolvePort(options.oauthPort)

  const serverMetadata: client.ServerMetadata = {
    issuer: new URL('/api/v1/oauth', url).href,
    authorization_endpoint: new URL('/api/v1/oauth/authorize', url).href,
    token_endpoint: new URL('/api/v1/oauth/token', url).href,
  }
  const config = new client.Configuration(
    serverMetadata,
    CLIENT_ID,
    undefined,
    client.None(),
  )
  // Self-hosted dev instances may use plain http://. The token endpoint call
  // still uses whatever protocol the user configured.
  if (url.startsWith('http://')) {
    client.allowInsecureRequests(config)
  }

  const codeVerifier = client.randomPKCECodeVerifier()
  const codeChallenge = await client.calculatePKCECodeChallenge(codeVerifier)
  const state = client.randomState()

  // Set up the local HTTP callback server.
  let resolveCallback: (url: URL) => void = () => {}
  let rejectCallback: (err: Error) => void = () => {}
  const callbackPromise = new Promise<URL>((resolve, reject) => {
    resolveCallback = resolve
    rejectCallback = reject
  })

  const server = http.createServer((req, res) => {
    if (!req.url?.startsWith(CALLBACK_PATH)) {
      res.writeHead(404, { 'Content-Type': 'text/plain' })
      res.end('Not Found')
      return
    }
    const callbackUrl = new URL(req.url, `http://localhost:${port}`)
    const errorParam = callbackUrl.searchParams.get('error')
    if (errorParam) {
      const desc =
        callbackUrl.searchParams.get('error_description') ?? errorParam
      res.writeHead(400, { 'Content-Type': 'text/html; charset=utf-8' })
      res.end(errorHtml(desc))
      rejectCallback(
        new CliError(
          'OAuth authorization denied',
          `The Lightdash authorization server returned: ${desc}`,
          `Try again, or paste a token manually: ldash setup ${url} --pat`,
        ),
      )
      return
    }
    if (
      !callbackUrl.searchParams.get('code') ||
      !callbackUrl.searchParams.get('state')
    ) {
      res.writeHead(400, { 'Content-Type': 'text/html; charset=utf-8' })
      res.end(errorHtml('Missing authorization code or state.'))
      rejectCallback(
        new CliError(
          'OAuth callback missing code or state',
          'The redirect from Lightdash did not include the expected parameters.',
          `Try again. If it keeps failing, use: ldash setup ${url} --pat`,
        ),
      )
      return
    }
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    res.end(successHtml())
    resolveCallback(callbackUrl)
  })

  // Start listening.
  await new Promise<void>((resolve, reject) => {
    server.once('error', reject)
    server.listen(port, '127.0.0.1', () => {
      const address = server.address()
      if (address && typeof address === 'object') {
        port = address.port
      }
      onServerReady?.(port)
      resolve()
    })
  })

  const redirectUri = `http://localhost:${port}/callback`

  let timeoutHandle: NodeJS.Timeout | undefined

  try {
    const authUrl = client.buildAuthorizationUrl(config, {
      redirect_uri: redirectUri,
      scope: 'read write',
      code_challenge: codeChallenge,
      code_challenge_method: 'S256',
      state,
    })

    onAuthUrlReady?.(authUrl.href)
    await openBrowser(authUrl.href)

    const timeoutPromise = new Promise<URL>((_, reject) => {
      timeoutHandle = setTimeout(() => {
        reject(
          new CliError(
            `Sign-in timed out after ${Math.round(timeoutMs / 1000)} seconds`,
            'No response was received from the browser.',
            [
              'Did your browser actually open the sign-in page?',
              'Behind a firewall? Try:  ldash setup --oauth-port 8976',
              `Can't use a browser? Try:  ldash setup ${url} --pat`,
            ].join('\n      '),
          ),
        )
      }, timeoutMs)
    })

    const currentUrl = await Promise.race([callbackPromise, timeoutPromise])

    let tokens: client.TokenEndpointResponse
    try {
      tokens = await client.authorizationCodeGrant(config, currentUrl, {
        pkceCodeVerifier: codeVerifier,
        expectedState: state,
      })
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      throw new CliError(
        'OAuth token exchange failed',
        msg,
        `Your Lightdash instance may not support CLI OAuth login yet.\n      Try:  ldash setup ${url} --pat`,
      )
    }

    const accessToken = tokens.access_token
    if (!accessToken) {
      throw new CliError(
        'OAuth token exchange returned no access token',
        'Lightdash responded successfully but did not include an access_token.',
        `Try:  ldash setup ${url} --pat`,
      )
    }

    const { token: pat, expiresAt } = await generatePat(
      url,
      accessToken,
      tokenTtlHours,
    )
    const user = await fetchUser(url, pat)

    return { token: pat, expiresAt, user }
  } finally {
    if (timeoutHandle) clearTimeout(timeoutHandle)
    server.close()
  }
}
